// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// distance
NumericVector distance(NumericMatrix sims, NumericVector obs);
RcppExport SEXP _sbizombies_distance(SEXP simsSEXP, SEXP obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type sims(simsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type obs(obsSEXP);
    rcpp_result_gen = Rcpp::wrap(distance(sims, obs));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _sbizombies_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// sirc
NumericMatrix sirc(NumericMatrix theta, double N, double S0, double I0, double R0, double tf, bool initial);
RcppExport SEXP _sbizombies_sirc(SEXP thetaSEXP, SEXP NSEXP, SEXP S0SEXP, SEXP I0SEXP, SEXP R0SEXP, SEXP tfSEXP, SEXP initialSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type I0(I0SEXP);
    Rcpp::traits::input_parameter< double >::type R0(R0SEXP);
    Rcpp::traits::input_parameter< double >::type tf(tfSEXP);
    Rcpp::traits::input_parameter< bool >::type initial(initialSEXP);
    rcpp_result_gen = Rcpp::wrap(sirc(theta, N, S0, I0, R0, tf, initial));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sbizombies_distance", (DL_FUNC) &_sbizombies_distance, 2},
    {"_sbizombies_rcpp_hello_world", (DL_FUNC) &_sbizombies_rcpp_hello_world, 0},
    {"_sbizombies_sirc", (DL_FUNC) &_sbizombies_sirc, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_sbizombies(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
