// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// abc_mcmc
NumericMatrix abc_mcmc(NumericVector obs, int N, NumericVector sd, NumericMatrix prior_params, double epsilon);
RcppExport SEXP _sbizombies_abc_mcmc(SEXP obsSEXP, SEXP NSEXP, SEXP sdSEXP, SEXP prior_paramsSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type prior_params(prior_paramsSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(abc_mcmc(obs, N, sd, prior_params, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// distance
NumericVector distance(NumericMatrix sims, NumericVector obs);
RcppExport SEXP _sbizombies_distance(SEXP simsSEXP, SEXP obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type sims(simsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type obs(obsSEXP);
    rcpp_result_gen = Rcpp::wrap(distance(sims, obs));
    return rcpp_result_gen;
END_RCPP
}
// dprior
double dprior(NumericVector vals, NumericMatrix params);
RcppExport SEXP _sbizombies_dprior(SEXP valsSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(dprior(vals, params));
    return rcpp_result_gen;
END_RCPP
}
// prop_mech
NumericVector prop_mech(NumericVector old, NumericVector sd);
RcppExport SEXP _sbizombies_prop_mech(SEXP oldSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type old(oldSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(prop_mech(old, sd));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _sbizombies_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// sirc
NumericMatrix sirc(NumericMatrix theta, double N, double tf, bool initial);
RcppExport SEXP _sbizombies_sirc(SEXP thetaSEXP, SEXP NSEXP, SEXP tfSEXP, SEXP initialSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type tf(tfSEXP);
    Rcpp::traits::input_parameter< bool >::type initial(initialSEXP);
    rcpp_result_gen = Rcpp::wrap(sirc(theta, N, tf, initial));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sbizombies_abc_mcmc", (DL_FUNC) &_sbizombies_abc_mcmc, 5},
    {"_sbizombies_distance", (DL_FUNC) &_sbizombies_distance, 2},
    {"_sbizombies_dprior", (DL_FUNC) &_sbizombies_dprior, 2},
    {"_sbizombies_prop_mech", (DL_FUNC) &_sbizombies_prop_mech, 2},
    {"_sbizombies_rcpp_hello_world", (DL_FUNC) &_sbizombies_rcpp_hello_world, 0},
    {"_sbizombies_sirc", (DL_FUNC) &_sbizombies_sirc, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_sbizombies(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
