---
title: "Compare posterior means"
author: "Daniel Ward"
date: "24/05/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Imports
```{r message=FALSE}
library(tidyverse)
theme_set(theme_bw())
```
 
 
## Read in pseudo-observed data
```{r}
pod_list = list()
for (i in 1:100){
  pod_file = paste0("pods/pod_theta_", i, ".txt")
  data = read.table(pod_file, col.names = c("beta", "gamma"))
  pod_list = append(pod_list, list(data))
}

true_parameters = do.call("rbind", pod_list)
true_parameters$pod_idx = 1:100
true_parameters = true_parameters %>%
  pivot_longer(cols = c(beta, gamma), names_to = "parameter", values_to = "true_parameters")
```

## Read in predicted means
```{r}
algorithms = c("rej", "mcmc")

data_list = list()
for (algorithm in algorithms){
  data_file = paste0("posterior_means/", algorithm, "_posterior_means.txt")
  alg_df = read.table(data_file, col.names = c("beta", "gamma"))
  alg_df$algorithm = algorithm
  alg_df$pod_idx = 1:100
  data_list = append(data_list, list(alg_df))
}

posterior_means = do.call("rbind", data_list)
posterior_means = posterior_means %>%
  pivot_longer(cols = c(beta, gamma), names_to = "parameter", values_to = "inferred_parameter_value")
posterior_means
```

## Combine both data frames
```{r}
df = left_join(posterior_means, true_parameters, by = c("pod_idx", "parameter"))
df$algorithm[df$algorithm == "rej"] = "rejection"
```

## MCMC acceptance rate
```{r}
acceptance_rates = c()
for (i in 1:100){
  data_file = paste0("mcmc_results/mcmc_posterior_", i, ".txt")
  df_ = read.table(data_file, col.names = c("beta", "gamma"))
  acceptance_rates = c(acceptance_rates, length(unique(df_$beta))/length(df_$beta))
}

print(mean(acceptance_rates))
print(median(acceptance_rates))
```


## Plot predicted vs observed
```{r}
p1 = ggplot(df, aes(true_parameters, inferred_parameter_value)) +
  geom_point() +
  facet_grid(parameter~algorithm, scales = "fixed") +
  geom_abline(slope=1, colour = "brown") +
  labs(x = "True parameter value", y = "Inferred parameter value")
p1
```

```{r}
ggsave("plots/true_vs_predicted.png", p1, width = 6, height = 3.5, dpi = 600)
```

## Plot RMSE
```{r}
df$rmse = sqrt((df$inferred_parameter_value - df$true_parameters)^2)
```

```{r}
p2 = ggplot(df, aes(y = rmse, x = algorithm)) +
  geom_boxplot(fill = "lightgrey") +
  facet_wrap(~parameter, scales = "free") +
  stat_summary(fun=mean, geom="point", shape=4, size=3, color="black", fill="red") +
  labs(x = "Algorithm", y = "Root mean square error")
p2
```

```{r}
ggsave("plots/rmse_boxplot.png", p2, width = 6, height = 3.5, dpi = 600)
```


## Logprob metric
```{r}
logprobs_df = read.csv("metrics/logprobs.csv")
logprobs_df = logprobs_df %>%
  pivot_longer(everything(), names_to = "algorithm", values_to = "negative_log_prob")
```


```{r}
p3 = ggplot(logprobs_df, aes(y = negative_log_prob, x = algorithm)) +
  geom_boxplot(fill = "lightgrey") +
  stat_summary(fun=mean, geom="point", shape=4, size=3, color="black", fill="red") +
  labs(x = "Algorithm", y = "Negative log-probability")
  
p3
```

```{r}
ggsave("plots/neg_log_boxplot.png", p3, width = 6, height = 3.5, dpi = 600)
```

