# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

abc_mcmc <- function(obs, N, sd, prior_params, epsilon, scale_ss) {
    .Call('_sbizombies_abc_mcmc', PACKAGE = 'sbizombies', obs, N, sd, prior_params, epsilon, scale_ss)
}

#' @export
distance <- function(sims, obs) {
    .Call('_sbizombies_distance', PACKAGE = 'sbizombies', sims, obs)
}

dprior <- function(vals, params) {
    .Call('_sbizombies_dprior', PACKAGE = 'sbizombies', vals, params)
}

prop_mech <- function(old, sd) {
    .Call('_sbizombies_prop_mech', PACKAGE = 'sbizombies', old, sd)
}

rcpp_hello_world <- function() {
    .Call('_sbizombies_rcpp_hello_world', PACKAGE = 'sbizombies')
}

szr <- function(theta, N, tf, initial = TRUE) {
    .Call('_sbizombies_szr', PACKAGE = 'sbizombies', theta, N, tf, initial)
}

