# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
distance <- function(sims, obs) {
    .Call(`_sbizombies_distance`, sims, obs)
}

rcpp_hello_world <- function() {
    .Call(`_sbizombies_rcpp_hello_world`)
}

sirc <- function(beta, gamma, iota, N, S0, I0, R0, tf, initial = TRUE, Nruns = 1L) {
    .Call(`_sbizombies_sirc`, beta, gamma, iota, N, S0, I0, R0, tf, initial, Nruns)
}

