# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

abc_mcmc <- function(obs, N, sd, prior_params, epsilon) {
    .Call(`_sbizombies_abc_mcmc`, obs, N, sd, prior_params, epsilon)
}

#' @export
distance <- function(sims, obs) {
    .Call(`_sbizombies_distance`, sims, obs)
}

dprior <- function(vals, params) {
    .Call(`_sbizombies_dprior`, vals, params)
}

prop_mech <- function(old, sd) {
    .Call(`_sbizombies_prop_mech`, old, sd)
}

rcpp_hello_world <- function() {
    .Call(`_sbizombies_rcpp_hello_world`)
}

szr <- function(theta, N, tf, initial = TRUE) {
    .Call(`_sbizombies_szr`, theta, N, tf, initial)
}

